amcl:
  ros__parameters:
    use_sim_time: true
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: BodyLink
    beam_skip_distance: 0.5
    do_beamskip: true


    
    global_frame_id: map
    laser_model_type: likelihood_field
    max_beams: 60
    min_particles: 500
    max_particles: 2000
    odom_frame_id: odom
    pf_err: 0.05
    pf_z: 0.99
    resample_interval: 1
    robot_model_type: differential
    save_pose_rate: 0.5
    scan_topic: scan
    set_initial_pose: true
    tf_broadcast: true
    update_min_d: 0.25
    update_min_a: 0.2

map_server:
  ros__parameters:
    use_sim_time: true
    yaml_filename: /home/exhausted/maps/map.yaml

planner_server:
  ros__parameters:
    use_sim_time: true
    expected_planner_frequency: 5.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: false
      allow_unknown: true

controller_server:
  ros__parameters:
    use_sim_time: true
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller/RegulatedPurePursuitController"
      desired_linear_vel: 0.4
      lookahead_dist: 0.6
      min_lookahead_dist: 0.3
      max_lookahead_dist: 1.5
      transform_tolerance: 0.2
    base_frame_id: BodyLink
    odom_frame_id: odom

behavior_server:
  ros__parameters:
    use_sim_time: true
    behaviors: ["spin", "backup", "wait"]
    spin:
      plugin: "nav2_behaviors/Spin"
    backup:
      plugin: "nav2_behaviors/BackUp"
    wait:
      plugin: "nav2_behaviors/Wait"

bt_navigator:
  ros__parameters:
    use_sim_time: true
    global_frame: map
    robot_base_frame: BodyLink
    default_nav_to_pose_bt_xml: "navigate_w_replanning_and_recovery.xml"

waypoint_follower:
  ros__parameters:
    use_sim_time: true
    stop_on_failure: false
    loop_rate: 20

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: true
      update_frequency: 10.0
      publish_frequency: 10.0
      global_frame: odom
      robot_base_frame: BodyLink
      width: 3.0
      height: 3.0
      resolution: 0.05
      rolling_window: true
      plugins: ["voxel_layer", "inflation_layer"]
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: true
        max_obstacle_height: 2.0
        origin_z: 0.0
        z_resolution: 0.2
        z_voxels: 10
        mark_threshold: 0
        observation_sources: scan
        scan:
          topic: scan
          max_obstacle_height: 2.0
          min_obstacle_height: 0.0
          obstacle_range: 2.5
          raytrace_range: 3.0
          data_type: LaserScan
          clearing: true
          marking: true
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: true
        inflation_radius: 0.5

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: true
      update_frequency: 2.0
      publish_frequency: 2.0
      global_frame: map
      robot_base_frame: BodyLink
      width: 10.0
      height: 10.0
      resolution: 0.05
      rolling_window: false
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        enabled: true
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        observation_sources: scan
        scan:
          topic: scan
          max_obstacle_height: 2.0
          min_obstacle_height: 0.0
          obstacle_range: 3.0
          raytrace_range: 3.5
          data_type: LaserScan
          clearing: true
          marking: true
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: true
        inflation_radius: 0.5

velocity_smoother:
  ros__parameters:
    use_sim_time: true
    smoothing_frequency: 20.0
    scale_velocities: false
    max_velocity: 0.6
    min_velocity: 0.0

lifecycle_manager:
  ros__parameters:
    use_sim_time: true
    autostart: true
    node_names:
      - map_server
      - planner_server
      - controller_server
      - bt_navigator
      - velocity_smoother
      - behavior_server
      - waypoint_follower
